# Generated by Django 3.0.2 on 2020-11-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('slot_number', models.IntegerField()),
                ('available_2_seater_tables', models.IntegerField()),
                ('available_4_seater_tables', models.IntegerField()),
                ('available_6_seater_tables', models.IntegerField()),
                ('available_8_seater_tables', models.IntegerField()),
            ],
        ),
    ]
