# Generated by Django 3.1.3 on 2020-12-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='experience',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
