# Generated by Django 3.0.2 on 2020-11-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0003_auto_20201126_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='tables',
            new_name='tables_2',
        ),
        migrations.AddField(
            model_name='table',
            name='tables_4',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='table',
            name='tables_6',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='table',
            name='tables_8',
            field=models.IntegerField(default=1),
        ),
    ]
