# Generated by Django 3.1.3 on 2020-11-27 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='active',
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable',
            field=models.CharField(default='ALL USERS', max_length=100),
        ),
        migrations.AddField(
            model_name='coupon',
            name='title',
            field=models.CharField(default='Mega Discount', max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
