# Generated by Django 3.1.3 on 2020-12-10 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, null=True)),
                ('order', models.TextField(null=True)),
                ('message', models.TextField()),
                ('viewed', models.BooleanField(default=False)),
                ('curr_user', models.TextField(max_length=30)),
                ('type', models.CharField(choices=[('GENERAL', 'General'), ('ORDER', 'Order'), ('PAYMENT', 'Payment'), ('App', 'App')], default='PERSONAL', max_length=8)),
                ('dest_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
